// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userAuthorizationEngine_grpc_api.proto

package userAuthorizationEngine_grpc_api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//~/Programs/protoc-3.13.0-linux-x86_64/bin/protoc  -I ../grpc_api/userAuthorizationEngine_grpc_api --go_out=plugins=grpc:../grpc_api/userAuthorizationEngine_grpc_api ../grpc_api/userAuthorizationEngine_grpc_api/qml_grpc_server.proto
// Parameter used for Empty inputs
type EmptyParameter struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyParameter) Reset()         { *m = EmptyParameter{} }
func (m *EmptyParameter) String() string { return proto.CompactTextString(m) }
func (*EmptyParameter) ProtoMessage()    {}
func (*EmptyParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_f486cd898f074c5b, []int{0}
}

func (m *EmptyParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyParameter.Unmarshal(m, b)
}
func (m *EmptyParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyParameter.Marshal(b, m, deterministic)
}
func (m *EmptyParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyParameter.Merge(m, src)
}
func (m *EmptyParameter) XXX_Size() int {
	return xxx_messageInfo_EmptyParameter.Size(m)
}
func (m *EmptyParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyParameter.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyParameter proto.InternalMessageInfo

// Ack/Nack- Response message with comment
type AckNackResponse struct {
	Acknack              bool     `protobuf:"varint,1,opt,name=acknack,proto3" json:"acknack,omitempty"`
	Comments             string   `protobuf:"bytes,2,opt,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckNackResponse) Reset()         { *m = AckNackResponse{} }
func (m *AckNackResponse) String() string { return proto.CompactTextString(m) }
func (*AckNackResponse) ProtoMessage()    {}
func (*AckNackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f486cd898f074c5b, []int{1}
}

func (m *AckNackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckNackResponse.Unmarshal(m, b)
}
func (m *AckNackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckNackResponse.Marshal(b, m, deterministic)
}
func (m *AckNackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckNackResponse.Merge(m, src)
}
func (m *AckNackResponse) XXX_Size() int {
	return xxx_messageInfo_AckNackResponse.Size(m)
}
func (m *AckNackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AckNackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AckNackResponse proto.InternalMessageInfo

func (m *AckNackResponse) GetAcknack() bool {
	if m != nil {
		return m.Acknack
	}
	return false
}

func (m *AckNackResponse) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

// *********************************************************************
// Request message with parameters for Boolean Rule engine
type UserAuthorizationRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CompanyId            string   `protobuf:"bytes,2,opt,name=companyId,proto3" json:"companyId,omitempty"`
	CallingApi           string   `protobuf:"bytes,3,opt,name=callingApi,proto3" json:"callingApi,omitempty"`
	Account              string   `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"`
	AccountType          string   `protobuf:"bytes,5,opt,name=accountType,proto3" json:"accountType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAuthorizationRequest) Reset()         { *m = UserAuthorizationRequest{} }
func (m *UserAuthorizationRequest) String() string { return proto.CompactTextString(m) }
func (*UserAuthorizationRequest) ProtoMessage()    {}
func (*UserAuthorizationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f486cd898f074c5b, []int{2}
}

func (m *UserAuthorizationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAuthorizationRequest.Unmarshal(m, b)
}
func (m *UserAuthorizationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAuthorizationRequest.Marshal(b, m, deterministic)
}
func (m *UserAuthorizationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAuthorizationRequest.Merge(m, src)
}
func (m *UserAuthorizationRequest) XXX_Size() int {
	return xxx_messageInfo_UserAuthorizationRequest.Size(m)
}
func (m *UserAuthorizationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAuthorizationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserAuthorizationRequest proto.InternalMessageInfo

func (m *UserAuthorizationRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserAuthorizationRequest) GetCompanyId() string {
	if m != nil {
		return m.CompanyId
	}
	return ""
}

func (m *UserAuthorizationRequest) GetCallingApi() string {
	if m != nil {
		return m.CallingApi
	}
	return ""
}

func (m *UserAuthorizationRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *UserAuthorizationRequest) GetAccountType() string {
	if m != nil {
		return m.AccountType
	}
	return ""
}

// Response message from Boolean Rule Engine
type UserAuthorizationResponse struct {
	UserIsAllowedToExecuteCallingApi bool     `protobuf:"varint,1,opt,name=userIsAllowedToExecuteCallingApi,proto3" json:"userIsAllowedToExecuteCallingApi,omitempty"`
	Acknack                          bool     `protobuf:"varint,3,opt,name=acknack,proto3" json:"acknack,omitempty"`
	Comments                         string   `protobuf:"bytes,4,opt,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral             struct{} `json:"-"`
	XXX_unrecognized                 []byte   `json:"-"`
	XXX_sizecache                    int32    `json:"-"`
}

func (m *UserAuthorizationResponse) Reset()         { *m = UserAuthorizationResponse{} }
func (m *UserAuthorizationResponse) String() string { return proto.CompactTextString(m) }
func (*UserAuthorizationResponse) ProtoMessage()    {}
func (*UserAuthorizationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f486cd898f074c5b, []int{3}
}

func (m *UserAuthorizationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAuthorizationResponse.Unmarshal(m, b)
}
func (m *UserAuthorizationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAuthorizationResponse.Marshal(b, m, deterministic)
}
func (m *UserAuthorizationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAuthorizationResponse.Merge(m, src)
}
func (m *UserAuthorizationResponse) XXX_Size() int {
	return xxx_messageInfo_UserAuthorizationResponse.Size(m)
}
func (m *UserAuthorizationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAuthorizationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserAuthorizationResponse proto.InternalMessageInfo

func (m *UserAuthorizationResponse) GetUserIsAllowedToExecuteCallingApi() bool {
	if m != nil {
		return m.UserIsAllowedToExecuteCallingApi
	}
	return false
}

func (m *UserAuthorizationResponse) GetAcknack() bool {
	if m != nil {
		return m.Acknack
	}
	return false
}

func (m *UserAuthorizationResponse) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

func init() {
	proto.RegisterType((*EmptyParameter)(nil), "userAuthorizationEngine_grpc_api.EmptyParameter")
	proto.RegisterType((*AckNackResponse)(nil), "userAuthorizationEngine_grpc_api.AckNackResponse")
	proto.RegisterType((*UserAuthorizationRequest)(nil), "userAuthorizationEngine_grpc_api.UserAuthorizationRequest")
	proto.RegisterType((*UserAuthorizationResponse)(nil), "userAuthorizationEngine_grpc_api.UserAuthorizationResponse")
}

func init() {
	proto.RegisterFile("userAuthorizationEngine_grpc_api.proto", fileDescriptor_f486cd898f074c5b)
}

var fileDescriptor_f486cd898f074c5b = []byte{
	// 371 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xc1, 0x6e, 0xda, 0x40,
	0x10, 0x86, 0x31, 0x50, 0x0a, 0x53, 0xa9, 0x45, 0x7b, 0xa8, 0x5c, 0x84, 0x5a, 0xcb, 0x87, 0x8a,
	0x13, 0x6a, 0x93, 0x5b, 0x72, 0xb2, 0x12, 0x84, 0x9c, 0x43, 0x14, 0x19, 0x72, 0x46, 0x9b, 0xf5,
	0x08, 0x2c, 0xdb, 0xbb, 0x9b, 0xf5, 0x3a, 0x84, 0x3c, 0x41, 0x2e, 0x79, 0x84, 0xbc, 0x41, 0x5e,
	0x20, 0x6f, 0x17, 0x61, 0x4c, 0x30, 0x10, 0x64, 0x29, 0x37, 0xff, 0x33, 0xb3, 0x3b, 0xbf, 0xbf,
	0x99, 0x85, 0xbf, 0x69, 0x82, 0xca, 0x49, 0xf5, 0x4c, 0xa8, 0xe0, 0x81, 0xea, 0x40, 0xf0, 0x01,
	0x9f, 0x06, 0x1c, 0x27, 0x53, 0x25, 0xd9, 0x84, 0xca, 0xa0, 0x2f, 0x95, 0xd0, 0x82, 0x58, 0x65,
	0x75, 0x76, 0x1b, 0xbe, 0x0f, 0x62, 0xa9, 0x17, 0x57, 0x54, 0xd1, 0x18, 0x35, 0x2a, 0x7b, 0x08,
	0x3f, 0x1c, 0x16, 0x5e, 0x52, 0x16, 0x7a, 0x98, 0x48, 0xc1, 0x13, 0x24, 0x26, 0x7c, 0xa5, 0x2c,
	0xe4, 0x94, 0x85, 0xa6, 0x61, 0x19, 0xbd, 0xa6, 0xb7, 0x96, 0xa4, 0x03, 0x4d, 0x26, 0xe2, 0x18,
	0xb9, 0x4e, 0xcc, 0xaa, 0x65, 0xf4, 0x5a, 0xde, 0xbb, 0xb6, 0x5f, 0x0c, 0x30, 0xaf, 0x77, 0xfb,
	0x7b, 0x78, 0x9b, 0x62, 0xa2, 0xc9, 0x4f, 0x68, 0x2c, 0xbd, 0xb9, 0x7e, 0x76, 0x63, 0xcb, 0xcb,
	0x15, 0xe9, 0x42, 0x8b, 0x89, 0x58, 0x52, 0xbe, 0x70, 0xfd, 0xfc, 0xc6, 0x4d, 0x80, 0xfc, 0x06,
	0x60, 0x34, 0x8a, 0x02, 0x3e, 0x75, 0x64, 0x60, 0xd6, 0xb2, 0x74, 0x21, 0xb2, 0x32, 0xca, 0x44,
	0xca, 0xb5, 0x59, 0xcf, 0x92, 0x6b, 0x49, 0x2c, 0xf8, 0x96, 0x7f, 0x8e, 0x17, 0x12, 0xcd, 0x2f,
	0x59, 0xb6, 0x18, 0xb2, 0x9f, 0x0d, 0xf8, 0xf5, 0x81, 0xdd, 0x1c, 0xc1, 0x05, 0x64, 0x2c, 0xdd,
	0xc4, 0x89, 0x22, 0x31, 0x47, 0x7f, 0x2c, 0x06, 0xf7, 0xc8, 0x52, 0x8d, 0x67, 0x1b, 0x3f, 0x2b,
	0x36, 0xa5, 0x75, 0x45, 0x9c, 0xb5, 0xc3, 0x38, 0xeb, 0xdb, 0x38, 0x8f, 0x5e, 0xab, 0xd0, 0xdd,
	0x1b, 0xe7, 0x50, 0x49, 0x36, 0x42, 0x75, 0x17, 0x30, 0x24, 0x4f, 0x06, 0xb4, 0xdd, 0xa4, 0xf8,
	0x0b, 0xe8, 0x93, 0x93, 0x7e, 0xe9, 0xaa, 0x1c, 0x9a, 0x51, 0xe7, 0xf4, 0x53, 0x67, 0x57, 0xc0,
	0xec, 0x0a, 0x79, 0x34, 0xe0, 0xcf, 0x68, 0x96, 0xea, 0x73, 0x31, 0xe7, 0x7b, 0x75, 0x4b, 0xd3,
	0xa8, 0xc8, 0xbf, 0xf2, 0x16, 0xdb, 0xeb, 0xd9, 0xf9, 0x5f, 0x7e, 0x62, 0x67, 0x7d, 0xed, 0xca,
	0x4d, 0x23, 0x7b, 0x0e, 0xc7, 0x6f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xce, 0x99, 0xdb, 0x93, 0x38,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserAuthorizationGrpcServiceClient is the client API for UserAuthorizationGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserAuthorizationGrpcServiceClient interface {
	// Do a user have the correct rights to execute a specific API
	IsUserAuthorized(ctx context.Context, in *UserAuthorizationRequest, opts ...grpc.CallOption) (*UserAuthorizationResponse, error)
	// Shutdown server in a controlled way
	ShutDownUserAuthorizationServer(ctx context.Context, in *EmptyParameter, opts ...grpc.CallOption) (*AckNackResponse, error)
}

type userAuthorizationGrpcServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserAuthorizationGrpcServiceClient(cc *grpc.ClientConn) UserAuthorizationGrpcServiceClient {
	return &userAuthorizationGrpcServiceClient{cc}
}

func (c *userAuthorizationGrpcServiceClient) IsUserAuthorized(ctx context.Context, in *UserAuthorizationRequest, opts ...grpc.CallOption) (*UserAuthorizationResponse, error) {
	out := new(UserAuthorizationResponse)
	err := c.cc.Invoke(ctx, "/userAuthorizationEngine_grpc_api.userAuthorizationGrpcService/IsUserAuthorized", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userAuthorizationGrpcServiceClient) ShutDownUserAuthorizationServer(ctx context.Context, in *EmptyParameter, opts ...grpc.CallOption) (*AckNackResponse, error) {
	out := new(AckNackResponse)
	err := c.cc.Invoke(ctx, "/userAuthorizationEngine_grpc_api.userAuthorizationGrpcService/ShutDownUserAuthorizationServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserAuthorizationGrpcServiceServer is the server API for UserAuthorizationGrpcService service.
type UserAuthorizationGrpcServiceServer interface {
	// Do a user have the correct rights to execute a specific API
	IsUserAuthorized(context.Context, *UserAuthorizationRequest) (*UserAuthorizationResponse, error)
	// Shutdown server in a controlled way
	ShutDownUserAuthorizationServer(context.Context, *EmptyParameter) (*AckNackResponse, error)
}

// UnimplementedUserAuthorizationGrpcServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserAuthorizationGrpcServiceServer struct {
}

func (*UnimplementedUserAuthorizationGrpcServiceServer) IsUserAuthorized(ctx context.Context, req *UserAuthorizationRequest) (*UserAuthorizationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsUserAuthorized not implemented")
}
func (*UnimplementedUserAuthorizationGrpcServiceServer) ShutDownUserAuthorizationServer(ctx context.Context, req *EmptyParameter) (*AckNackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShutDownUserAuthorizationServer not implemented")
}

func RegisterUserAuthorizationGrpcServiceServer(s *grpc.Server, srv UserAuthorizationGrpcServiceServer) {
	s.RegisterService(&_UserAuthorizationGrpcService_serviceDesc, srv)
}

func _UserAuthorizationGrpcService_IsUserAuthorized_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAuthorizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAuthorizationGrpcServiceServer).IsUserAuthorized(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userAuthorizationEngine_grpc_api.userAuthorizationGrpcService/IsUserAuthorized",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAuthorizationGrpcServiceServer).IsUserAuthorized(ctx, req.(*UserAuthorizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserAuthorizationGrpcService_ShutDownUserAuthorizationServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyParameter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserAuthorizationGrpcServiceServer).ShutDownUserAuthorizationServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userAuthorizationEngine_grpc_api.userAuthorizationGrpcService/ShutDownUserAuthorizationServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserAuthorizationGrpcServiceServer).ShutDownUserAuthorizationServer(ctx, req.(*EmptyParameter))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserAuthorizationGrpcService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "userAuthorizationEngine_grpc_api.userAuthorizationGrpcService",
	HandlerType: (*UserAuthorizationGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsUserAuthorized",
			Handler:    _UserAuthorizationGrpcService_IsUserAuthorized_Handler,
		},
		{
			MethodName: "ShutDownUserAuthorizationServer",
			Handler:    _UserAuthorizationGrpcService_ShutDownUserAuthorizationServer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "userAuthorizationEngine_grpc_api.proto",
}
