// Code generated by protoc-gen-go. DO NOT EDIT.
// source: a3s_grpc_api.proto

package a3s_grpc_api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//~/Programs/protoc-3.13.0-linux-x86_64/bin/protoc  -I ../grpc_api/qml_server_grpc_api --go_out=plugins=grpc:../grpc_api/qml_server_grpc_api ../grpc_api/qml_server_grpc_api/qml_grpc_server.proto
// Parameter used for Empty inputs
type EmptyParameter struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyParameter) Reset()         { *m = EmptyParameter{} }
func (m *EmptyParameter) String() string { return proto.CompactTextString(m) }
func (*EmptyParameter) ProtoMessage()    {}
func (*EmptyParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_3471e42b66f8aed8, []int{0}
}

func (m *EmptyParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyParameter.Unmarshal(m, b)
}
func (m *EmptyParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyParameter.Marshal(b, m, deterministic)
}
func (m *EmptyParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyParameter.Merge(m, src)
}
func (m *EmptyParameter) XXX_Size() int {
	return xxx_messageInfo_EmptyParameter.Size(m)
}
func (m *EmptyParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyParameter.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyParameter proto.InternalMessageInfo

// Ack/Nack- Response message with comment
type AckNackResponse struct {
	Acknack              bool     `protobuf:"varint,1,opt,name=acknack,proto3" json:"acknack,omitempty"`
	Comments             string   `protobuf:"bytes,2,opt,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckNackResponse) Reset()         { *m = AckNackResponse{} }
func (m *AckNackResponse) String() string { return proto.CompactTextString(m) }
func (*AckNackResponse) ProtoMessage()    {}
func (*AckNackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3471e42b66f8aed8, []int{1}
}

func (m *AckNackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckNackResponse.Unmarshal(m, b)
}
func (m *AckNackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckNackResponse.Marshal(b, m, deterministic)
}
func (m *AckNackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckNackResponse.Merge(m, src)
}
func (m *AckNackResponse) XXX_Size() int {
	return xxx_messageInfo_AckNackResponse.Size(m)
}
func (m *AckNackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AckNackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AckNackResponse proto.InternalMessageInfo

func (m *AckNackResponse) GetAcknack() bool {
	if m != nil {
		return m.Acknack
	}
	return false
}

func (m *AckNackResponse) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

// Request message when updating a users authorization signature
type UpdateUserAggregatedSignatureRequest struct {
	UserId                  string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	UserAggregatedSignature string   `protobuf:"bytes,2,opt,name=userAggregatedSignature,proto3" json:"userAggregatedSignature,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *UpdateUserAggregatedSignatureRequest) Reset()         { *m = UpdateUserAggregatedSignatureRequest{} }
func (m *UpdateUserAggregatedSignatureRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserAggregatedSignatureRequest) ProtoMessage()    {}
func (*UpdateUserAggregatedSignatureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3471e42b66f8aed8, []int{2}
}

func (m *UpdateUserAggregatedSignatureRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserAggregatedSignatureRequest.Unmarshal(m, b)
}
func (m *UpdateUserAggregatedSignatureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserAggregatedSignatureRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserAggregatedSignatureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserAggregatedSignatureRequest.Merge(m, src)
}
func (m *UpdateUserAggregatedSignatureRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserAggregatedSignatureRequest.Size(m)
}
func (m *UpdateUserAggregatedSignatureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserAggregatedSignatureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserAggregatedSignatureRequest proto.InternalMessageInfo

func (m *UpdateUserAggregatedSignatureRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpdateUserAggregatedSignatureRequest) GetUserAggregatedSignature() string {
	if m != nil {
		return m.UserAggregatedSignature
	}
	return ""
}

// Request message when reading a users authorization signature
type GetUserAggregatedSignatureRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserAggregatedSignatureRequest) Reset()         { *m = GetUserAggregatedSignatureRequest{} }
func (m *GetUserAggregatedSignatureRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserAggregatedSignatureRequest) ProtoMessage()    {}
func (*GetUserAggregatedSignatureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3471e42b66f8aed8, []int{3}
}

func (m *GetUserAggregatedSignatureRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserAggregatedSignatureRequest.Unmarshal(m, b)
}
func (m *GetUserAggregatedSignatureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserAggregatedSignatureRequest.Marshal(b, m, deterministic)
}
func (m *GetUserAggregatedSignatureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserAggregatedSignatureRequest.Merge(m, src)
}
func (m *GetUserAggregatedSignatureRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserAggregatedSignatureRequest.Size(m)
}
func (m *GetUserAggregatedSignatureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserAggregatedSignatureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserAggregatedSignatureRequest proto.InternalMessageInfo

func (m *GetUserAggregatedSignatureRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

// Response message when reading a users authorization Signature
type GetUserAggregatedSignatureResponse struct {
	UserId                  string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	UserAggregatedSignature string   `protobuf:"bytes,2,opt,name=userAggregatedSignature,proto3" json:"userAggregatedSignature,omitempty"`
	Acknack                 bool     `protobuf:"varint,3,opt,name=acknack,proto3" json:"acknack,omitempty"`
	Comments                string   `protobuf:"bytes,4,opt,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *GetUserAggregatedSignatureResponse) Reset()         { *m = GetUserAggregatedSignatureResponse{} }
func (m *GetUserAggregatedSignatureResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserAggregatedSignatureResponse) ProtoMessage()    {}
func (*GetUserAggregatedSignatureResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3471e42b66f8aed8, []int{4}
}

func (m *GetUserAggregatedSignatureResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserAggregatedSignatureResponse.Unmarshal(m, b)
}
func (m *GetUserAggregatedSignatureResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserAggregatedSignatureResponse.Marshal(b, m, deterministic)
}
func (m *GetUserAggregatedSignatureResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserAggregatedSignatureResponse.Merge(m, src)
}
func (m *GetUserAggregatedSignatureResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserAggregatedSignatureResponse.Size(m)
}
func (m *GetUserAggregatedSignatureResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserAggregatedSignatureResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserAggregatedSignatureResponse proto.InternalMessageInfo

func (m *GetUserAggregatedSignatureResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetUserAggregatedSignatureResponse) GetUserAggregatedSignature() string {
	if m != nil {
		return m.UserAggregatedSignature
	}
	return ""
}

func (m *GetUserAggregatedSignatureResponse) GetAcknack() bool {
	if m != nil {
		return m.Acknack
	}
	return false
}

func (m *GetUserAggregatedSignatureResponse) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

func init() {
	proto.RegisterType((*EmptyParameter)(nil), "a3s_grpc_api.EmptyParameter")
	proto.RegisterType((*AckNackResponse)(nil), "a3s_grpc_api.AckNackResponse")
	proto.RegisterType((*UpdateUserAggregatedSignatureRequest)(nil), "a3s_grpc_api.UpdateUserAggregatedSignatureRequest")
	proto.RegisterType((*GetUserAggregatedSignatureRequest)(nil), "a3s_grpc_api.GetUserAggregatedSignatureRequest")
	proto.RegisterType((*GetUserAggregatedSignatureResponse)(nil), "a3s_grpc_api.GetUserAggregatedSignatureResponse")
}

func init() { proto.RegisterFile("a3s_grpc_api.proto", fileDescriptor_3471e42b66f8aed8) }

var fileDescriptor_3471e42b66f8aed8 = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xc1, 0x4a, 0x3b, 0x31,
	0x10, 0xc6, 0xff, 0xdb, 0xbf, 0xd4, 0x76, 0x90, 0xaa, 0x39, 0x68, 0x59, 0x14, 0xda, 0xe0, 0xa1,
	0xa7, 0x2a, 0xdd, 0x8b, 0xe0, 0x69, 0x41, 0x29, 0x5e, 0x44, 0x76, 0xe9, 0xb9, 0xc4, 0x74, 0xd8,
	0x2e, 0xcb, 0x6e, 0x62, 0x32, 0xab, 0xd5, 0x9b, 0xef, 0xe3, 0x53, 0xf9, 0x24, 0x62, 0xa9, 0x6d,
	0x23, 0xd6, 0x16, 0xf1, 0x38, 0x09, 0xdf, 0x7c, 0x93, 0xdf, 0x7c, 0x01, 0x26, 0x02, 0x3b, 0x4c,
	0x8c, 0x96, 0x43, 0xa1, 0xd3, 0xae, 0x36, 0x8a, 0x14, 0xdb, 0x59, 0x3e, 0xe3, 0x7b, 0xd0, 0xb8,
	0xca, 0x35, 0x3d, 0xdd, 0x0a, 0x23, 0x72, 0x24, 0x34, 0xbc, 0x0f, 0xbb, 0xa1, 0xcc, 0x6e, 0x84,
	0xcc, 0x22, 0xb4, 0x5a, 0x15, 0x16, 0x59, 0x13, 0xb6, 0x85, 0xcc, 0x0a, 0x21, 0xb3, 0xa6, 0xd7,
	0xf2, 0x3a, 0xb5, 0xe8, 0xb3, 0x64, 0x3e, 0xd4, 0xa4, 0xca, 0x73, 0x2c, 0xc8, 0x36, 0x2b, 0x2d,
	0xaf, 0x53, 0x8f, 0xe6, 0x35, 0x9f, 0xc0, 0xc9, 0x40, 0x8f, 0x04, 0xe1, 0xc0, 0xa2, 0x09, 0x93,
	0xc4, 0x60, 0x22, 0x08, 0x47, 0x71, 0x9a, 0x14, 0x82, 0x4a, 0x83, 0x11, 0xde, 0x97, 0x68, 0x89,
	0x1d, 0x40, 0xb5, 0xb4, 0x68, 0xae, 0x47, 0xd3, 0xe6, 0xf5, 0x68, 0x56, 0xb1, 0x73, 0x38, 0x2c,
	0xbf, 0x57, 0xce, 0xac, 0x56, 0x5d, 0xf3, 0x0b, 0x68, 0xf7, 0x91, 0x7e, 0x67, 0xcb, 0x5f, 0x3d,
	0xe0, 0x3f, 0xa9, 0x67, 0x4c, 0xfe, 0x7c, 0xea, 0x65, 0xca, 0xff, 0x57, 0x53, 0xde, 0x72, 0x29,
	0xf7, 0xde, 0x2a, 0xd0, 0x08, 0x83, 0xb8, 0x6f, 0xb4, 0x8c, 0xd1, 0x3c, 0xa4, 0x12, 0xd9, 0x04,
	0xda, 0x0b, 0xf0, 0x36, 0x2c, 0x69, 0xac, 0x4c, 0xfa, 0x2c, 0x28, 0x55, 0xc5, 0xc2, 0xad, 0xd7,
	0x75, 0xb2, 0xb1, 0xc9, 0xa6, 0xfc, 0x63, 0x57, 0xf3, 0x25, 0x26, 0xfc, 0x1f, 0x7b, 0xf1, 0xc0,
	0x5f, 0xcd, 0x8e, 0x9d, 0xba, 0xfa, 0xb5, 0x3b, 0xf2, 0xcf, 0x36, 0x17, 0xcc, 0x67, 0x88, 0x60,
	0x3f, 0x1e, 0x97, 0x74, 0xa9, 0x1e, 0x8b, 0x30, 0x88, 0x3f, 0x98, 0xa0, 0x61, 0x47, 0x6e, 0x23,
	0x37, 0xf2, 0x6b, 0xdf, 0x75, 0x57, 0x9d, 0x7e, 0x9d, 0xe0, 0x3d, 0x00, 0x00, 0xff, 0xff, 0xc4,
	0x2b, 0x59, 0xbe, 0x50, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// A3SGrpcServiceClient is the client API for A3SGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type A3SGrpcServiceClient interface {
	// Updates a specifics users aggregated signature
	UpdateUsersAuthorizationSignature(ctx context.Context, in *UpdateUserAggregatedSignatureRequest, opts ...grpc.CallOption) (*AckNackResponse, error)
	// Reads a specific users aggregated signature
	GetUserAggregatedSignature(ctx context.Context, in *GetUserAggregatedSignatureRequest, opts ...grpc.CallOption) (*GetUserAggregatedSignatureResponse, error)
	// Shut down server in a controlled way
	ShutDownA3SServer(ctx context.Context, in *EmptyParameter, opts ...grpc.CallOption) (*AckNackResponse, error)
}

type a3SGrpcServiceClient struct {
	cc *grpc.ClientConn
}

func NewA3SGrpcServiceClient(cc *grpc.ClientConn) A3SGrpcServiceClient {
	return &a3SGrpcServiceClient{cc}
}

func (c *a3SGrpcServiceClient) UpdateUsersAuthorizationSignature(ctx context.Context, in *UpdateUserAggregatedSignatureRequest, opts ...grpc.CallOption) (*AckNackResponse, error) {
	out := new(AckNackResponse)
	err := c.cc.Invoke(ctx, "/a3s_grpc_api.A3SGrpcService/UpdateUsersAuthorizationSignature", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *a3SGrpcServiceClient) GetUserAggregatedSignature(ctx context.Context, in *GetUserAggregatedSignatureRequest, opts ...grpc.CallOption) (*GetUserAggregatedSignatureResponse, error) {
	out := new(GetUserAggregatedSignatureResponse)
	err := c.cc.Invoke(ctx, "/a3s_grpc_api.A3SGrpcService/GetUserAggregatedSignature", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *a3SGrpcServiceClient) ShutDownA3SServer(ctx context.Context, in *EmptyParameter, opts ...grpc.CallOption) (*AckNackResponse, error) {
	out := new(AckNackResponse)
	err := c.cc.Invoke(ctx, "/a3s_grpc_api.A3SGrpcService/ShutDownA3SServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// A3SGrpcServiceServer is the server API for A3SGrpcService service.
type A3SGrpcServiceServer interface {
	// Updates a specifics users aggregated signature
	UpdateUsersAuthorizationSignature(context.Context, *UpdateUserAggregatedSignatureRequest) (*AckNackResponse, error)
	// Reads a specific users aggregated signature
	GetUserAggregatedSignature(context.Context, *GetUserAggregatedSignatureRequest) (*GetUserAggregatedSignatureResponse, error)
	// Shut down server in a controlled way
	ShutDownA3SServer(context.Context, *EmptyParameter) (*AckNackResponse, error)
}

// UnimplementedA3SGrpcServiceServer can be embedded to have forward compatible implementations.
type UnimplementedA3SGrpcServiceServer struct {
}

func (*UnimplementedA3SGrpcServiceServer) UpdateUsersAuthorizationSignature(ctx context.Context, req *UpdateUserAggregatedSignatureRequest) (*AckNackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUsersAuthorizationSignature not implemented")
}
func (*UnimplementedA3SGrpcServiceServer) GetUserAggregatedSignature(ctx context.Context, req *GetUserAggregatedSignatureRequest) (*GetUserAggregatedSignatureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserAggregatedSignature not implemented")
}
func (*UnimplementedA3SGrpcServiceServer) ShutDownA3SServer(ctx context.Context, req *EmptyParameter) (*AckNackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShutDownA3SServer not implemented")
}

func RegisterA3SGrpcServiceServer(s *grpc.Server, srv A3SGrpcServiceServer) {
	s.RegisterService(&_A3SGrpcService_serviceDesc, srv)
}

func _A3SGrpcService_UpdateUsersAuthorizationSignature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserAggregatedSignatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(A3SGrpcServiceServer).UpdateUsersAuthorizationSignature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/a3s_grpc_api.A3SGrpcService/UpdateUsersAuthorizationSignature",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(A3SGrpcServiceServer).UpdateUsersAuthorizationSignature(ctx, req.(*UpdateUserAggregatedSignatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _A3SGrpcService_GetUserAggregatedSignature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserAggregatedSignatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(A3SGrpcServiceServer).GetUserAggregatedSignature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/a3s_grpc_api.A3SGrpcService/GetUserAggregatedSignature",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(A3SGrpcServiceServer).GetUserAggregatedSignature(ctx, req.(*GetUserAggregatedSignatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _A3SGrpcService_ShutDownA3SServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyParameter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(A3SGrpcServiceServer).ShutDownA3SServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/a3s_grpc_api.A3SGrpcService/ShutDownA3SServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(A3SGrpcServiceServer).ShutDownA3SServer(ctx, req.(*EmptyParameter))
	}
	return interceptor(ctx, in, info, handler)
}

var _A3SGrpcService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "a3s_grpc_api.A3SGrpcService",
	HandlerType: (*A3SGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateUsersAuthorizationSignature",
			Handler:    _A3SGrpcService_UpdateUsersAuthorizationSignature_Handler,
		},
		{
			MethodName: "GetUserAggregatedSignature",
			Handler:    _A3SGrpcService_GetUserAggregatedSignature_Handler,
		},
		{
			MethodName: "ShutDownA3SServer",
			Handler:    _A3SGrpcService_ShutDownA3SServer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "a3s_grpc_api.proto",
}
