// Code generated by protoc-gen-go. DO NOT EDIT.
// source: secretMessageGenerator_grpc_api.proto

package secretMessageGenerator_grpc_api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//~/Programs/protoc-3.13.0-linux-x86_64/bin/protoc  -I ../grpc_api/qml_server_grpc_api --go_out=plugins=grpc:../grpc_api/qml_server_grpc_api ../grpc_api/qml_server_grpc_api/qml_grpc_server.proto
// Parameter used for Empty inputs
type EmptyParameter struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyParameter) Reset()         { *m = EmptyParameter{} }
func (m *EmptyParameter) String() string { return proto.CompactTextString(m) }
func (*EmptyParameter) ProtoMessage()    {}
func (*EmptyParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2bf9140ba153fb4, []int{0}
}

func (m *EmptyParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyParameter.Unmarshal(m, b)
}
func (m *EmptyParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyParameter.Marshal(b, m, deterministic)
}
func (m *EmptyParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyParameter.Merge(m, src)
}
func (m *EmptyParameter) XXX_Size() int {
	return xxx_messageInfo_EmptyParameter.Size(m)
}
func (m *EmptyParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyParameter.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyParameter proto.InternalMessageInfo

// Ack/Nack- Response message with comment
type AckNackResponse struct {
	Acknack              bool     `protobuf:"varint,1,opt,name=acknack,proto3" json:"acknack,omitempty"`
	Comments             string   `protobuf:"bytes,2,opt,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckNackResponse) Reset()         { *m = AckNackResponse{} }
func (m *AckNackResponse) String() string { return proto.CompactTextString(m) }
func (*AckNackResponse) ProtoMessage()    {}
func (*AckNackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2bf9140ba153fb4, []int{1}
}

func (m *AckNackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckNackResponse.Unmarshal(m, b)
}
func (m *AckNackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckNackResponse.Marshal(b, m, deterministic)
}
func (m *AckNackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckNackResponse.Merge(m, src)
}
func (m *AckNackResponse) XXX_Size() int {
	return xxx_messageInfo_AckNackResponse.Size(m)
}
func (m *AckNackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AckNackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AckNackResponse proto.InternalMessageInfo

func (m *AckNackResponse) GetAcknack() bool {
	if m != nil {
		return m.Acknack
	}
	return false
}

func (m *AckNackResponse) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

// Request message when to create the secret message used when signing
type GenerateSecretFromInputRequest struct {
	UserId               string         `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Company              string         `protobuf:"bytes,2,opt,name=company,proto3" json:"company,omitempty"`
	Accounts             []*Account     `protobuf:"bytes,3,rep,name=accounts,proto3" json:"accounts,omitempty"`
	AccountTypes         []*AccountType `protobuf:"bytes,4,rep,name=accountTypes,proto3" json:"accountTypes,omitempty"`
	Companies            []*Company     `protobuf:"bytes,5,rep,name=companies,proto3" json:"companies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GenerateSecretFromInputRequest) Reset()         { *m = GenerateSecretFromInputRequest{} }
func (m *GenerateSecretFromInputRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateSecretFromInputRequest) ProtoMessage()    {}
func (*GenerateSecretFromInputRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2bf9140ba153fb4, []int{2}
}

func (m *GenerateSecretFromInputRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateSecretFromInputRequest.Unmarshal(m, b)
}
func (m *GenerateSecretFromInputRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateSecretFromInputRequest.Marshal(b, m, deterministic)
}
func (m *GenerateSecretFromInputRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateSecretFromInputRequest.Merge(m, src)
}
func (m *GenerateSecretFromInputRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateSecretFromInputRequest.Size(m)
}
func (m *GenerateSecretFromInputRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateSecretFromInputRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateSecretFromInputRequest proto.InternalMessageInfo

func (m *GenerateSecretFromInputRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GenerateSecretFromInputRequest) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *GenerateSecretFromInputRequest) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func (m *GenerateSecretFromInputRequest) GetAccountTypes() []*AccountType {
	if m != nil {
		return m.AccountTypes
	}
	return nil
}

func (m *GenerateSecretFromInputRequest) GetCompanies() []*Company {
	if m != nil {
		return m.Companies
	}
	return nil
}

// Response message used when signing
type GenerateSecretFromInputResponse struct {
	Secret               string   `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Acknack              bool     `protobuf:"varint,2,opt,name=acknack,proto3" json:"acknack,omitempty"`
	Comments             string   `protobuf:"bytes,3,opt,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateSecretFromInputResponse) Reset()         { *m = GenerateSecretFromInputResponse{} }
func (m *GenerateSecretFromInputResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateSecretFromInputResponse) ProtoMessage()    {}
func (*GenerateSecretFromInputResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2bf9140ba153fb4, []int{3}
}

func (m *GenerateSecretFromInputResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateSecretFromInputResponse.Unmarshal(m, b)
}
func (m *GenerateSecretFromInputResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateSecretFromInputResponse.Marshal(b, m, deterministic)
}
func (m *GenerateSecretFromInputResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateSecretFromInputResponse.Merge(m, src)
}
func (m *GenerateSecretFromInputResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateSecretFromInputResponse.Size(m)
}
func (m *GenerateSecretFromInputResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateSecretFromInputResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateSecretFromInputResponse proto.InternalMessageInfo

func (m *GenerateSecretFromInputResponse) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *GenerateSecretFromInputResponse) GetAcknack() bool {
	if m != nil {
		return m.Acknack
	}
	return false
}

func (m *GenerateSecretFromInputResponse) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

//  Holds the account that the user has access to
type Account struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2bf9140ba153fb4, []int{4}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

//  Holds the account type that the user has access to
type AccountType struct {
	AccountType          string   `protobuf:"bytes,1,opt,name=accountType,proto3" json:"accountType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountType) Reset()         { *m = AccountType{} }
func (m *AccountType) String() string { return proto.CompactTextString(m) }
func (*AccountType) ProtoMessage()    {}
func (*AccountType) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2bf9140ba153fb4, []int{5}
}

func (m *AccountType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountType.Unmarshal(m, b)
}
func (m *AccountType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountType.Marshal(b, m, deterministic)
}
func (m *AccountType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountType.Merge(m, src)
}
func (m *AccountType) XXX_Size() int {
	return xxx_messageInfo_AccountType.Size(m)
}
func (m *AccountType) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountType.DiscardUnknown(m)
}

var xxx_messageInfo_AccountType proto.InternalMessageInfo

func (m *AccountType) GetAccountType() string {
	if m != nil {
		return m.AccountType
	}
	return ""
}

//  Holds the company type that the user has access to
type Company struct {
	Company              string   `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Company) Reset()         { *m = Company{} }
func (m *Company) String() string { return proto.CompactTextString(m) }
func (*Company) ProtoMessage()    {}
func (*Company) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2bf9140ba153fb4, []int{6}
}

func (m *Company) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Company.Unmarshal(m, b)
}
func (m *Company) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Company.Marshal(b, m, deterministic)
}
func (m *Company) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Company.Merge(m, src)
}
func (m *Company) XXX_Size() int {
	return xxx_messageInfo_Company.Size(m)
}
func (m *Company) XXX_DiscardUnknown() {
	xxx_messageInfo_Company.DiscardUnknown(m)
}

var xxx_messageInfo_Company proto.InternalMessageInfo

func (m *Company) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func init() {
	proto.RegisterType((*EmptyParameter)(nil), "secretMessageGenerator_grpc_api.EmptyParameter")
	proto.RegisterType((*AckNackResponse)(nil), "secretMessageGenerator_grpc_api.AckNackResponse")
	proto.RegisterType((*GenerateSecretFromInputRequest)(nil), "secretMessageGenerator_grpc_api.GenerateSecretFromInputRequest")
	proto.RegisterType((*GenerateSecretFromInputResponse)(nil), "secretMessageGenerator_grpc_api.GenerateSecretFromInputResponse")
	proto.RegisterType((*Account)(nil), "secretMessageGenerator_grpc_api.Account")
	proto.RegisterType((*AccountType)(nil), "secretMessageGenerator_grpc_api.AccountType")
	proto.RegisterType((*Company)(nil), "secretMessageGenerator_grpc_api.Company")
}

func init() {
	proto.RegisterFile("secretMessageGenerator_grpc_api.proto", fileDescriptor_d2bf9140ba153fb4)
}

var fileDescriptor_d2bf9140ba153fb4 = []byte{
	// 405 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4d, 0xce, 0xd3, 0x30,
	0x10, 0x6d, 0x52, 0xe8, 0xcf, 0x14, 0x01, 0xf2, 0xa2, 0x44, 0x5d, 0xd0, 0x10, 0x40, 0xca, 0x02,
	0xb5, 0xa8, 0x1c, 0x00, 0x2a, 0x4a, 0xab, 0x2e, 0x40, 0x95, 0xcb, 0xbe, 0x32, 0x66, 0x54, 0xaa,
	0x28, 0xb1, 0xb1, 0x1d, 0x50, 0xcf, 0xc0, 0x1d, 0x38, 0x04, 0x47, 0xe1, 0x44, 0x28, 0x89, 0x53,
	0x92, 0x4f, 0xed, 0x97, 0xea, 0xdb, 0xf9, 0x59, 0x9e, 0x37, 0xf3, 0xde, 0xf3, 0xc0, 0x4b, 0x8d,
	0x5c, 0xa1, 0xf9, 0x88, 0x5a, 0xb3, 0x3d, 0xae, 0x30, 0x41, 0xc5, 0x8c, 0x50, 0xbb, 0xbd, 0x92,
	0x7c, 0xc7, 0xe4, 0x61, 0x22, 0x95, 0x30, 0x82, 0x8c, 0x1b, 0x9e, 0x05, 0x8f, 0xe1, 0xe1, 0x87,
	0x58, 0x9a, 0xe3, 0x86, 0x29, 0x16, 0xa3, 0x41, 0x15, 0xac, 0xe0, 0xd1, 0x9c, 0x47, 0x9f, 0x18,
	0x8f, 0x28, 0x6a, 0x29, 0x12, 0x8d, 0xc4, 0x83, 0x2e, 0xe3, 0x51, 0xc2, 0x78, 0xe4, 0x39, 0xbe,
	0x13, 0xf6, 0x68, 0x09, 0xc9, 0x08, 0x7a, 0x5c, 0xc4, 0x31, 0x26, 0x46, 0x7b, 0xae, 0xef, 0x84,
	0x7d, 0x7a, 0xc2, 0xc1, 0x1f, 0x17, 0x9e, 0xda, 0x8e, 0xb8, 0xcd, 0xc7, 0x58, 0x2a, 0x11, 0xaf,
	0x13, 0x99, 0x1a, 0x8a, 0xdf, 0x53, 0xd4, 0x86, 0x0c, 0xa1, 0x93, 0x6a, 0x54, 0xeb, 0xaf, 0x39,
	0x6f, 0x9f, 0x5a, 0x94, 0x35, 0xe4, 0x22, 0x96, 0x2c, 0x39, 0x5a, 0xd6, 0x12, 0x92, 0x05, 0xf4,
	0x18, 0xe7, 0x22, 0xcd, 0x1a, 0xb6, 0xfd, 0x76, 0x38, 0x98, 0x85, 0x93, 0x26, 0x2b, 0xe6, 0x45,
	0x01, 0x3d, 0x55, 0x92, 0x0d, 0x3c, 0xb0, 0xe7, 0xcf, 0x47, 0x89, 0xda, 0xbb, 0x97, 0x33, 0xbd,
	0xba, 0x96, 0x29, 0x2b, 0xa2, 0x35, 0x06, 0xb2, 0x84, 0x7e, 0x31, 0xe2, 0x01, 0xb5, 0x77, 0xff,
	0xca, 0xc1, 0xde, 0x17, 0xa2, 0xe8, 0xff, 0xd2, 0x40, 0xc0, 0xf8, 0xa2, 0x67, 0x36, 0x8d, 0x21,
	0x74, 0x0a, 0xe2, 0xd2, 0xb4, 0x02, 0x55, 0x53, 0x72, 0x2f, 0xa7, 0xd4, 0xbe, 0x91, 0xd2, 0x73,
	0xe8, 0x5a, 0x55, 0x05, 0x41, 0x7e, 0xb4, 0xcc, 0x25, 0x0c, 0xa6, 0x30, 0xa8, 0x48, 0x27, 0x3e,
	0x0c, 0x2a, 0xe2, 0xed, 0xe3, 0xea, 0x55, 0xc6, 0x6a, 0xc5, 0x55, 0xb3, 0x74, 0x6a, 0x59, 0xce,
	0xfe, 0xba, 0xf0, 0xec, 0xbc, 0x45, 0x2b, 0x25, 0xf9, 0x16, 0xd5, 0x8f, 0x03, 0x47, 0xf2, 0xdb,
	0x81, 0x27, 0x17, 0x2c, 0x21, 0x6f, 0x1b, 0x2d, 0xbe, 0xfd, 0x03, 0x8e, 0xde, 0xdd, 0x9d, 0xa0,
	0x48, 0x23, 0x68, 0x91, 0x5f, 0x0e, 0xbc, 0xd8, 0x7e, 0x4b, 0xcd, 0x42, 0xfc, 0x4c, 0xce, 0xb3,
	0x65, 0x52, 0x50, 0x91, 0x69, 0x63, 0xb3, 0xfa, 0x2a, 0x8e, 0x5e, 0x5f, 0xf1, 0x21, 0x6b, 0x9b,
	0x1a, 0xb4, 0xbe, 0x74, 0xf2, 0xc5, 0x7f, 0xf3, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x70, 0x6d, 0x80,
	0x19, 0x21, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SecretMessageGeneratorGrpcServiceClient is the client API for SecretMessageGeneratorGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SecretMessageGeneratorGrpcServiceClient interface {
	// Generate secrete used when signing
	GenerateSecretFromInput(ctx context.Context, in *GenerateSecretFromInputRequest, opts ...grpc.CallOption) (*GenerateSecretFromInputResponse, error)
	// Shut down server in a controlled way
	ShutDownsecretMessageGeneratorServer(ctx context.Context, in *EmptyParameter, opts ...grpc.CallOption) (*AckNackResponse, error)
}

type secretMessageGeneratorGrpcServiceClient struct {
	cc *grpc.ClientConn
}

func NewSecretMessageGeneratorGrpcServiceClient(cc *grpc.ClientConn) SecretMessageGeneratorGrpcServiceClient {
	return &secretMessageGeneratorGrpcServiceClient{cc}
}

func (c *secretMessageGeneratorGrpcServiceClient) GenerateSecretFromInput(ctx context.Context, in *GenerateSecretFromInputRequest, opts ...grpc.CallOption) (*GenerateSecretFromInputResponse, error) {
	out := new(GenerateSecretFromInputResponse)
	err := c.cc.Invoke(ctx, "/secretMessageGenerator_grpc_api.secretMessageGeneratorGrpcService/GenerateSecretFromInput", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretMessageGeneratorGrpcServiceClient) ShutDownsecretMessageGeneratorServer(ctx context.Context, in *EmptyParameter, opts ...grpc.CallOption) (*AckNackResponse, error) {
	out := new(AckNackResponse)
	err := c.cc.Invoke(ctx, "/secretMessageGenerator_grpc_api.secretMessageGeneratorGrpcService/ShutDownsecretMessageGeneratorServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecretMessageGeneratorGrpcServiceServer is the server API for SecretMessageGeneratorGrpcService service.
type SecretMessageGeneratorGrpcServiceServer interface {
	// Generate secrete used when signing
	GenerateSecretFromInput(context.Context, *GenerateSecretFromInputRequest) (*GenerateSecretFromInputResponse, error)
	// Shut down server in a controlled way
	ShutDownsecretMessageGeneratorServer(context.Context, *EmptyParameter) (*AckNackResponse, error)
}

// UnimplementedSecretMessageGeneratorGrpcServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSecretMessageGeneratorGrpcServiceServer struct {
}

func (*UnimplementedSecretMessageGeneratorGrpcServiceServer) GenerateSecretFromInput(ctx context.Context, req *GenerateSecretFromInputRequest) (*GenerateSecretFromInputResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateSecretFromInput not implemented")
}
func (*UnimplementedSecretMessageGeneratorGrpcServiceServer) ShutDownsecretMessageGeneratorServer(ctx context.Context, req *EmptyParameter) (*AckNackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShutDownsecretMessageGeneratorServer not implemented")
}

func RegisterSecretMessageGeneratorGrpcServiceServer(s *grpc.Server, srv SecretMessageGeneratorGrpcServiceServer) {
	s.RegisterService(&_SecretMessageGeneratorGrpcService_serviceDesc, srv)
}

func _SecretMessageGeneratorGrpcService_GenerateSecretFromInput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateSecretFromInputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretMessageGeneratorGrpcServiceServer).GenerateSecretFromInput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/secretMessageGenerator_grpc_api.secretMessageGeneratorGrpcService/GenerateSecretFromInput",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretMessageGeneratorGrpcServiceServer).GenerateSecretFromInput(ctx, req.(*GenerateSecretFromInputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretMessageGeneratorGrpcService_ShutDownsecretMessageGeneratorServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyParameter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretMessageGeneratorGrpcServiceServer).ShutDownsecretMessageGeneratorServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/secretMessageGenerator_grpc_api.secretMessageGeneratorGrpcService/ShutDownsecretMessageGeneratorServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretMessageGeneratorGrpcServiceServer).ShutDownsecretMessageGeneratorServer(ctx, req.(*EmptyParameter))
	}
	return interceptor(ctx, in, info, handler)
}

var _SecretMessageGeneratorGrpcService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "secretMessageGenerator_grpc_api.secretMessageGeneratorGrpcService",
	HandlerType: (*SecretMessageGeneratorGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateSecretFromInput",
			Handler:    _SecretMessageGeneratorGrpcService_GenerateSecretFromInput_Handler,
		},
		{
			MethodName: "ShutDownsecretMessageGeneratorServer",
			Handler:    _SecretMessageGeneratorGrpcService_ShutDownsecretMessageGeneratorServer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "secretMessageGenerator_grpc_api.proto",
}
