// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userRequests_grpc_api.proto

package userRequests_grpc_api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//~/Programs/protoc-3.13.0-linux-x86_64/bin/protoc  -I ../grpc_api/qml_server_grpc_api --go_out=plugins=grpc:../grpc_api/qml_server_grpc_api ../grpc_api/qml_server_grpc_api/qml_grpc_server.proto
// Parameter used for Empty inputs
type EmptyParameter struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyParameter) Reset()         { *m = EmptyParameter{} }
func (m *EmptyParameter) String() string { return proto.CompactTextString(m) }
func (*EmptyParameter) ProtoMessage()    {}
func (*EmptyParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_998c3be95f1b4ffb, []int{0}
}

func (m *EmptyParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyParameter.Unmarshal(m, b)
}
func (m *EmptyParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyParameter.Marshal(b, m, deterministic)
}
func (m *EmptyParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyParameter.Merge(m, src)
}
func (m *EmptyParameter) XXX_Size() int {
	return xxx_messageInfo_EmptyParameter.Size(m)
}
func (m *EmptyParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyParameter.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyParameter proto.InternalMessageInfo

// Ack/Nack- Response message with comment
type AckNackResponse struct {
	Acknack              bool     `protobuf:"varint,1,opt,name=acknack,proto3" json:"acknack,omitempty"`
	Comments             string   `protobuf:"bytes,2,opt,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckNackResponse) Reset()         { *m = AckNackResponse{} }
func (m *AckNackResponse) String() string { return proto.CompactTextString(m) }
func (*AckNackResponse) ProtoMessage()    {}
func (*AckNackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_998c3be95f1b4ffb, []int{1}
}

func (m *AckNackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckNackResponse.Unmarshal(m, b)
}
func (m *AckNackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckNackResponse.Marshal(b, m, deterministic)
}
func (m *AckNackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckNackResponse.Merge(m, src)
}
func (m *AckNackResponse) XXX_Size() int {
	return xxx_messageInfo_AckNackResponse.Size(m)
}
func (m *AckNackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AckNackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AckNackResponse proto.InternalMessageInfo

func (m *AckNackResponse) GetAcknack() bool {
	if m != nil {
		return m.Acknack
	}
	return false
}

func (m *AckNackResponse) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

// *********************************************************************
// Request message for listing accounts that a user is allowed to have
type ListAccountsRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CompanyId            string   `protobuf:"bytes,2,opt,name=companyId,proto3" json:"companyId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAccountsRequest) Reset()         { *m = ListAccountsRequest{} }
func (m *ListAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*ListAccountsRequest) ProtoMessage()    {}
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_998c3be95f1b4ffb, []int{2}
}

func (m *ListAccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsRequest.Unmarshal(m, b)
}
func (m *ListAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsRequest.Marshal(b, m, deterministic)
}
func (m *ListAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsRequest.Merge(m, src)
}
func (m *ListAccountsRequest) XXX_Size() int {
	return xxx_messageInfo_ListAccountsRequest.Size(m)
}
func (m *ListAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsRequest proto.InternalMessageInfo

func (m *ListAccountsRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ListAccountsRequest) GetCompanyId() string {
	if m != nil {
		return m.CompanyId
	}
	return ""
}

// Response message for listing accounts that a user is allowed to have
type ListAccountsResponse struct {
	UserId               string     `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CompanyId            string     `protobuf:"bytes,2,opt,name=companyId,proto3" json:"companyId,omitempty"`
	Acknack              bool       `protobuf:"varint,3,opt,name=acknack,proto3" json:"acknack,omitempty"`
	Comments             string     `protobuf:"bytes,4,opt,name=comments,proto3" json:"comments,omitempty"`
	Accounts             []*Account `protobuf:"bytes,5,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListAccountsResponse) Reset()         { *m = ListAccountsResponse{} }
func (m *ListAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*ListAccountsResponse) ProtoMessage()    {}
func (*ListAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_998c3be95f1b4ffb, []int{3}
}

func (m *ListAccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsResponse.Unmarshal(m, b)
}
func (m *ListAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsResponse.Marshal(b, m, deterministic)
}
func (m *ListAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsResponse.Merge(m, src)
}
func (m *ListAccountsResponse) XXX_Size() int {
	return xxx_messageInfo_ListAccountsResponse.Size(m)
}
func (m *ListAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsResponse proto.InternalMessageInfo

func (m *ListAccountsResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ListAccountsResponse) GetCompanyId() string {
	if m != nil {
		return m.CompanyId
	}
	return ""
}

func (m *ListAccountsResponse) GetAcknack() bool {
	if m != nil {
		return m.Acknack
	}
	return false
}

func (m *ListAccountsResponse) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

func (m *ListAccountsResponse) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

//  Holds the account that the user has access to
type Account struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_998c3be95f1b4ffb, []int{4}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

// Request message for listing accounts,based on type, that a user is allowed to have
type ListAccountsBasedOnProvidedTypeRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CompanyId            string   `protobuf:"bytes,2,opt,name=companyId,proto3" json:"companyId,omitempty"`
	AccounType           string   `protobuf:"bytes,3,opt,name=accounType,proto3" json:"accounType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAccountsBasedOnProvidedTypeRequest) Reset() {
	*m = ListAccountsBasedOnProvidedTypeRequest{}
}
func (m *ListAccountsBasedOnProvidedTypeRequest) String() string { return proto.CompactTextString(m) }
func (*ListAccountsBasedOnProvidedTypeRequest) ProtoMessage()    {}
func (*ListAccountsBasedOnProvidedTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_998c3be95f1b4ffb, []int{5}
}

func (m *ListAccountsBasedOnProvidedTypeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsBasedOnProvidedTypeRequest.Unmarshal(m, b)
}
func (m *ListAccountsBasedOnProvidedTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsBasedOnProvidedTypeRequest.Marshal(b, m, deterministic)
}
func (m *ListAccountsBasedOnProvidedTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsBasedOnProvidedTypeRequest.Merge(m, src)
}
func (m *ListAccountsBasedOnProvidedTypeRequest) XXX_Size() int {
	return xxx_messageInfo_ListAccountsBasedOnProvidedTypeRequest.Size(m)
}
func (m *ListAccountsBasedOnProvidedTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsBasedOnProvidedTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsBasedOnProvidedTypeRequest proto.InternalMessageInfo

func (m *ListAccountsBasedOnProvidedTypeRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ListAccountsBasedOnProvidedTypeRequest) GetCompanyId() string {
	if m != nil {
		return m.CompanyId
	}
	return ""
}

func (m *ListAccountsBasedOnProvidedTypeRequest) GetAccounType() string {
	if m != nil {
		return m.AccounType
	}
	return ""
}

// Response message for listing accounts,based on type, that a user is allowed to have
type ListAccountsBasedOnProvidedTypeResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CompanyId            string   `protobuf:"bytes,2,opt,name=companyId,proto3" json:"companyId,omitempty"`
	AccounType           string   `protobuf:"bytes,3,opt,name=accounType,proto3" json:"accounType,omitempty"`
	Acknack              bool     `protobuf:"varint,4,opt,name=acknack,proto3" json:"acknack,omitempty"`
	Comments             string   `protobuf:"bytes,5,opt,name=comments,proto3" json:"comments,omitempty"`
	JsonResponse         string   `protobuf:"bytes,6,opt,name=jsonResponse,proto3" json:"jsonResponse,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAccountsBasedOnProvidedTypeResponse) Reset() {
	*m = ListAccountsBasedOnProvidedTypeResponse{}
}
func (m *ListAccountsBasedOnProvidedTypeResponse) String() string { return proto.CompactTextString(m) }
func (*ListAccountsBasedOnProvidedTypeResponse) ProtoMessage()    {}
func (*ListAccountsBasedOnProvidedTypeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_998c3be95f1b4ffb, []int{6}
}

func (m *ListAccountsBasedOnProvidedTypeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsBasedOnProvidedTypeResponse.Unmarshal(m, b)
}
func (m *ListAccountsBasedOnProvidedTypeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsBasedOnProvidedTypeResponse.Marshal(b, m, deterministic)
}
func (m *ListAccountsBasedOnProvidedTypeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsBasedOnProvidedTypeResponse.Merge(m, src)
}
func (m *ListAccountsBasedOnProvidedTypeResponse) XXX_Size() int {
	return xxx_messageInfo_ListAccountsBasedOnProvidedTypeResponse.Size(m)
}
func (m *ListAccountsBasedOnProvidedTypeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsBasedOnProvidedTypeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsBasedOnProvidedTypeResponse proto.InternalMessageInfo

func (m *ListAccountsBasedOnProvidedTypeResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ListAccountsBasedOnProvidedTypeResponse) GetCompanyId() string {
	if m != nil {
		return m.CompanyId
	}
	return ""
}

func (m *ListAccountsBasedOnProvidedTypeResponse) GetAccounType() string {
	if m != nil {
		return m.AccounType
	}
	return ""
}

func (m *ListAccountsBasedOnProvidedTypeResponse) GetAcknack() bool {
	if m != nil {
		return m.Acknack
	}
	return false
}

func (m *ListAccountsBasedOnProvidedTypeResponse) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

func (m *ListAccountsBasedOnProvidedTypeResponse) GetJsonResponse() string {
	if m != nil {
		return m.JsonResponse
	}
	return ""
}

// *********************************************************************
// Request message for adding an account
type AddAccountRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CompanyId            string   `protobuf:"bytes,2,opt,name=companyId,proto3" json:"companyId,omitempty"`
	JsonRequest          string   `protobuf:"bytes,3,opt,name=jsonRequest,proto3" json:"jsonRequest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddAccountRequest) Reset()         { *m = AddAccountRequest{} }
func (m *AddAccountRequest) String() string { return proto.CompactTextString(m) }
func (*AddAccountRequest) ProtoMessage()    {}
func (*AddAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_998c3be95f1b4ffb, []int{7}
}

func (m *AddAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAccountRequest.Unmarshal(m, b)
}
func (m *AddAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAccountRequest.Marshal(b, m, deterministic)
}
func (m *AddAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAccountRequest.Merge(m, src)
}
func (m *AddAccountRequest) XXX_Size() int {
	return xxx_messageInfo_AddAccountRequest.Size(m)
}
func (m *AddAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddAccountRequest proto.InternalMessageInfo

func (m *AddAccountRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AddAccountRequest) GetCompanyId() string {
	if m != nil {
		return m.CompanyId
	}
	return ""
}

func (m *AddAccountRequest) GetJsonRequest() string {
	if m != nil {
		return m.JsonRequest
	}
	return ""
}

// Response message when adding an an account
type AddAccountResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CompanyId            string   `protobuf:"bytes,2,opt,name=companyId,proto3" json:"companyId,omitempty"`
	Acknack              bool     `protobuf:"varint,3,opt,name=acknack,proto3" json:"acknack,omitempty"`
	Comments             string   `protobuf:"bytes,4,opt,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddAccountResponse) Reset()         { *m = AddAccountResponse{} }
func (m *AddAccountResponse) String() string { return proto.CompactTextString(m) }
func (*AddAccountResponse) ProtoMessage()    {}
func (*AddAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_998c3be95f1b4ffb, []int{8}
}

func (m *AddAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAccountResponse.Unmarshal(m, b)
}
func (m *AddAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAccountResponse.Marshal(b, m, deterministic)
}
func (m *AddAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAccountResponse.Merge(m, src)
}
func (m *AddAccountResponse) XXX_Size() int {
	return xxx_messageInfo_AddAccountResponse.Size(m)
}
func (m *AddAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddAccountResponse proto.InternalMessageInfo

func (m *AddAccountResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AddAccountResponse) GetCompanyId() string {
	if m != nil {
		return m.CompanyId
	}
	return ""
}

func (m *AddAccountResponse) GetAcknack() bool {
	if m != nil {
		return m.Acknack
	}
	return false
}

func (m *AddAccountResponse) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

// *********************************************************************
// Request message for deleting an account
type DeleteAccountRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CompanyId            string   `protobuf:"bytes,2,opt,name=companyId,proto3" json:"companyId,omitempty"`
	Account              string   `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccountRequest) Reset()         { *m = DeleteAccountRequest{} }
func (m *DeleteAccountRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountRequest) ProtoMessage()    {}
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_998c3be95f1b4ffb, []int{9}
}

func (m *DeleteAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountRequest.Unmarshal(m, b)
}
func (m *DeleteAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountRequest.Merge(m, src)
}
func (m *DeleteAccountRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountRequest.Size(m)
}
func (m *DeleteAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountRequest proto.InternalMessageInfo

func (m *DeleteAccountRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *DeleteAccountRequest) GetCompanyId() string {
	if m != nil {
		return m.CompanyId
	}
	return ""
}

func (m *DeleteAccountRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

// Response message when adding an an account
type DeleteAccountResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CompanyId            string   `protobuf:"bytes,2,opt,name=companyId,proto3" json:"companyId,omitempty"`
	Acknack              bool     `protobuf:"varint,3,opt,name=acknack,proto3" json:"acknack,omitempty"`
	Comments             string   `protobuf:"bytes,4,opt,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccountResponse) Reset()         { *m = DeleteAccountResponse{} }
func (m *DeleteAccountResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountResponse) ProtoMessage()    {}
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_998c3be95f1b4ffb, []int{10}
}

func (m *DeleteAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountResponse.Unmarshal(m, b)
}
func (m *DeleteAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountResponse.Merge(m, src)
}
func (m *DeleteAccountResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountResponse.Size(m)
}
func (m *DeleteAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountResponse proto.InternalMessageInfo

func (m *DeleteAccountResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *DeleteAccountResponse) GetCompanyId() string {
	if m != nil {
		return m.CompanyId
	}
	return ""
}

func (m *DeleteAccountResponse) GetAcknack() bool {
	if m != nil {
		return m.Acknack
	}
	return false
}

func (m *DeleteAccountResponse) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

// *********************************************************************
// Request message for adding an account type
type AddAccountTypeRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CompanyId            string   `protobuf:"bytes,2,opt,name=companyId,proto3" json:"companyId,omitempty"`
	JsonAccountTypeData  string   `protobuf:"bytes,3,opt,name=jsonAccountTypeData,proto3" json:"jsonAccountTypeData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddAccountTypeRequest) Reset()         { *m = AddAccountTypeRequest{} }
func (m *AddAccountTypeRequest) String() string { return proto.CompactTextString(m) }
func (*AddAccountTypeRequest) ProtoMessage()    {}
func (*AddAccountTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_998c3be95f1b4ffb, []int{11}
}

func (m *AddAccountTypeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAccountTypeRequest.Unmarshal(m, b)
}
func (m *AddAccountTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAccountTypeRequest.Marshal(b, m, deterministic)
}
func (m *AddAccountTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAccountTypeRequest.Merge(m, src)
}
func (m *AddAccountTypeRequest) XXX_Size() int {
	return xxx_messageInfo_AddAccountTypeRequest.Size(m)
}
func (m *AddAccountTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAccountTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddAccountTypeRequest proto.InternalMessageInfo

func (m *AddAccountTypeRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AddAccountTypeRequest) GetCompanyId() string {
	if m != nil {
		return m.CompanyId
	}
	return ""
}

func (m *AddAccountTypeRequest) GetJsonAccountTypeData() string {
	if m != nil {
		return m.JsonAccountTypeData
	}
	return ""
}

// Response message when adding an account type
type AddAccountTypeResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CompanyId            string   `protobuf:"bytes,2,opt,name=companyId,proto3" json:"companyId,omitempty"`
	Acknack              bool     `protobuf:"varint,3,opt,name=acknack,proto3" json:"acknack,omitempty"`
	Comments             string   `protobuf:"bytes,4,opt,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddAccountTypeResponse) Reset()         { *m = AddAccountTypeResponse{} }
func (m *AddAccountTypeResponse) String() string { return proto.CompactTextString(m) }
func (*AddAccountTypeResponse) ProtoMessage()    {}
func (*AddAccountTypeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_998c3be95f1b4ffb, []int{12}
}

func (m *AddAccountTypeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAccountTypeResponse.Unmarshal(m, b)
}
func (m *AddAccountTypeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAccountTypeResponse.Marshal(b, m, deterministic)
}
func (m *AddAccountTypeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAccountTypeResponse.Merge(m, src)
}
func (m *AddAccountTypeResponse) XXX_Size() int {
	return xxx_messageInfo_AddAccountTypeResponse.Size(m)
}
func (m *AddAccountTypeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAccountTypeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddAccountTypeResponse proto.InternalMessageInfo

func (m *AddAccountTypeResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AddAccountTypeResponse) GetCompanyId() string {
	if m != nil {
		return m.CompanyId
	}
	return ""
}

func (m *AddAccountTypeResponse) GetAcknack() bool {
	if m != nil {
		return m.Acknack
	}
	return false
}

func (m *AddAccountTypeResponse) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

// *********************************************************************
// Request message for deleting an account type
type DeleteAccountTypeTypeRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CompanyId            string   `protobuf:"bytes,2,opt,name=companyId,proto3" json:"companyId,omitempty"`
	Account              string   `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccountTypeTypeRequest) Reset()         { *m = DeleteAccountTypeTypeRequest{} }
func (m *DeleteAccountTypeTypeRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountTypeTypeRequest) ProtoMessage()    {}
func (*DeleteAccountTypeTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_998c3be95f1b4ffb, []int{13}
}

func (m *DeleteAccountTypeTypeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountTypeTypeRequest.Unmarshal(m, b)
}
func (m *DeleteAccountTypeTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountTypeTypeRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAccountTypeTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountTypeTypeRequest.Merge(m, src)
}
func (m *DeleteAccountTypeTypeRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountTypeTypeRequest.Size(m)
}
func (m *DeleteAccountTypeTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountTypeTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountTypeTypeRequest proto.InternalMessageInfo

func (m *DeleteAccountTypeTypeRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *DeleteAccountTypeTypeRequest) GetCompanyId() string {
	if m != nil {
		return m.CompanyId
	}
	return ""
}

func (m *DeleteAccountTypeTypeRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

//Response message when deleting an account type
type DeleteAccountTypeResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CompanyId            string   `protobuf:"bytes,2,opt,name=companyId,proto3" json:"companyId,omitempty"`
	Acknack              bool     `protobuf:"varint,3,opt,name=acknack,proto3" json:"acknack,omitempty"`
	Comments             string   `protobuf:"bytes,4,opt,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccountTypeResponse) Reset()         { *m = DeleteAccountTypeResponse{} }
func (m *DeleteAccountTypeResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountTypeResponse) ProtoMessage()    {}
func (*DeleteAccountTypeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_998c3be95f1b4ffb, []int{14}
}

func (m *DeleteAccountTypeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountTypeResponse.Unmarshal(m, b)
}
func (m *DeleteAccountTypeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountTypeResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAccountTypeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountTypeResponse.Merge(m, src)
}
func (m *DeleteAccountTypeResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountTypeResponse.Size(m)
}
func (m *DeleteAccountTypeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountTypeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountTypeResponse proto.InternalMessageInfo

func (m *DeleteAccountTypeResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *DeleteAccountTypeResponse) GetCompanyId() string {
	if m != nil {
		return m.CompanyId
	}
	return ""
}

func (m *DeleteAccountTypeResponse) GetAcknack() bool {
	if m != nil {
		return m.Acknack
	}
	return false
}

func (m *DeleteAccountTypeResponse) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

// *********************************************************************
// Request message for updating company information
type UpdateCompanyInformationRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CompanyId            string   `protobuf:"bytes,2,opt,name=companyId,proto3" json:"companyId,omitempty"`
	JsonCompanyData      string   `protobuf:"bytes,3,opt,name=jsonCompanyData,proto3" json:"jsonCompanyData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCompanyInformationRequest) Reset()         { *m = UpdateCompanyInformationRequest{} }
func (m *UpdateCompanyInformationRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCompanyInformationRequest) ProtoMessage()    {}
func (*UpdateCompanyInformationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_998c3be95f1b4ffb, []int{15}
}

func (m *UpdateCompanyInformationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCompanyInformationRequest.Unmarshal(m, b)
}
func (m *UpdateCompanyInformationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCompanyInformationRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCompanyInformationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCompanyInformationRequest.Merge(m, src)
}
func (m *UpdateCompanyInformationRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCompanyInformationRequest.Size(m)
}
func (m *UpdateCompanyInformationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCompanyInformationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCompanyInformationRequest proto.InternalMessageInfo

func (m *UpdateCompanyInformationRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpdateCompanyInformationRequest) GetCompanyId() string {
	if m != nil {
		return m.CompanyId
	}
	return ""
}

func (m *UpdateCompanyInformationRequest) GetJsonCompanyData() string {
	if m != nil {
		return m.JsonCompanyData
	}
	return ""
}

// Response message when updating company information
type UpdateCompanyInformationResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CompanyId            string   `protobuf:"bytes,2,opt,name=companyId,proto3" json:"companyId,omitempty"`
	Acknack              bool     `protobuf:"varint,3,opt,name=acknack,proto3" json:"acknack,omitempty"`
	Comments             string   `protobuf:"bytes,4,opt,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCompanyInformationResponse) Reset()         { *m = UpdateCompanyInformationResponse{} }
func (m *UpdateCompanyInformationResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateCompanyInformationResponse) ProtoMessage()    {}
func (*UpdateCompanyInformationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_998c3be95f1b4ffb, []int{16}
}

func (m *UpdateCompanyInformationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCompanyInformationResponse.Unmarshal(m, b)
}
func (m *UpdateCompanyInformationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCompanyInformationResponse.Marshal(b, m, deterministic)
}
func (m *UpdateCompanyInformationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCompanyInformationResponse.Merge(m, src)
}
func (m *UpdateCompanyInformationResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateCompanyInformationResponse.Size(m)
}
func (m *UpdateCompanyInformationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCompanyInformationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCompanyInformationResponse proto.InternalMessageInfo

func (m *UpdateCompanyInformationResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpdateCompanyInformationResponse) GetCompanyId() string {
	if m != nil {
		return m.CompanyId
	}
	return ""
}

func (m *UpdateCompanyInformationResponse) GetAcknack() bool {
	if m != nil {
		return m.Acknack
	}
	return false
}

func (m *UpdateCompanyInformationResponse) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

func init() {
	proto.RegisterType((*EmptyParameter)(nil), "userRequests_grpc_api.EmptyParameter")
	proto.RegisterType((*AckNackResponse)(nil), "userRequests_grpc_api.AckNackResponse")
	proto.RegisterType((*ListAccountsRequest)(nil), "userRequests_grpc_api.ListAccountsRequest")
	proto.RegisterType((*ListAccountsResponse)(nil), "userRequests_grpc_api.ListAccountsResponse")
	proto.RegisterType((*Account)(nil), "userRequests_grpc_api.Account")
	proto.RegisterType((*ListAccountsBasedOnProvidedTypeRequest)(nil), "userRequests_grpc_api.ListAccountsBasedOnProvidedTypeRequest")
	proto.RegisterType((*ListAccountsBasedOnProvidedTypeResponse)(nil), "userRequests_grpc_api.ListAccountsBasedOnProvidedTypeResponse")
	proto.RegisterType((*AddAccountRequest)(nil), "userRequests_grpc_api.AddAccountRequest")
	proto.RegisterType((*AddAccountResponse)(nil), "userRequests_grpc_api.AddAccountResponse")
	proto.RegisterType((*DeleteAccountRequest)(nil), "userRequests_grpc_api.DeleteAccountRequest")
	proto.RegisterType((*DeleteAccountResponse)(nil), "userRequests_grpc_api.DeleteAccountResponse")
	proto.RegisterType((*AddAccountTypeRequest)(nil), "userRequests_grpc_api.AddAccountTypeRequest")
	proto.RegisterType((*AddAccountTypeResponse)(nil), "userRequests_grpc_api.AddAccountTypeResponse")
	proto.RegisterType((*DeleteAccountTypeTypeRequest)(nil), "userRequests_grpc_api.DeleteAccountTypeTypeRequest")
	proto.RegisterType((*DeleteAccountTypeResponse)(nil), "userRequests_grpc_api.DeleteAccountTypeResponse")
	proto.RegisterType((*UpdateCompanyInformationRequest)(nil), "userRequests_grpc_api.UpdateCompanyInformationRequest")
	proto.RegisterType((*UpdateCompanyInformationResponse)(nil), "userRequests_grpc_api.UpdateCompanyInformationResponse")
}

func init() { proto.RegisterFile("userRequests_grpc_api.proto", fileDescriptor_998c3be95f1b4ffb) }

var fileDescriptor_998c3be95f1b4ffb = []byte{
	// 665 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0xeb, 0x6e, 0xd3, 0x30,
	0x14, 0x9e, 0xd9, 0xb5, 0x67, 0x63, 0x63, 0xde, 0x85, 0x10, 0xa6, 0x51, 0x19, 0x31, 0x0a, 0x8c,
	0x69, 0xda, 0x24, 0x90, 0x90, 0x40, 0x2a, 0x14, 0x4d, 0x13, 0x08, 0xa6, 0x8c, 0xfd, 0x9e, 0x8c,
	0xe3, 0x41, 0xe8, 0x72, 0x21, 0x71, 0x87, 0x2a, 0x21, 0x2e, 0x02, 0x89, 0x5f, 0xf0, 0x0e, 0xbc,
	0x08, 0xef, 0xc1, 0x23, 0xf0, 0x16, 0x28, 0xa9, 0x9b, 0x3a, 0x59, 0xad, 0x86, 0x16, 0xad, 0xff,
	0xe2, 0x13, 0xfb, 0xfb, 0xbe, 0x73, 0x8e, 0xcf, 0x39, 0x86, 0xcb, 0x8d, 0x88, 0x87, 0x16, 0x7f,
	0xdb, 0xe0, 0x91, 0x88, 0x0e, 0x5f, 0x85, 0x01, 0x3b, 0xa4, 0x81, 0xb3, 0x11, 0x84, 0xbe, 0xf0,
	0xf1, 0x52, 0xd7, 0x9f, 0xe4, 0x02, 0xcc, 0x3e, 0x76, 0x03, 0xd1, 0xdc, 0xa3, 0x21, 0x75, 0xb9,
	0xe0, 0x21, 0xd9, 0x81, 0xb9, 0x2a, 0xab, 0x3f, 0xa3, 0xac, 0x6e, 0xf1, 0x28, 0xf0, 0xbd, 0x88,
	0x63, 0x03, 0x26, 0x29, 0xab, 0x7b, 0x94, 0xd5, 0x0d, 0x54, 0x46, 0x95, 0x29, 0xab, 0xbd, 0xc4,
	0x26, 0x4c, 0x31, 0xdf, 0x75, 0xb9, 0x27, 0x22, 0xe3, 0x5c, 0x19, 0x55, 0x4a, 0x56, 0xba, 0x26,
	0x4f, 0x60, 0xe1, 0xa9, 0x13, 0x89, 0x2a, 0x63, 0x7e, 0xc3, 0x13, 0x91, 0xe4, 0xc6, 0xcb, 0x30,
	0x11, 0x4b, 0xd9, 0xb5, 0x13, 0xac, 0x92, 0x25, 0x57, 0x78, 0x05, 0x4a, 0xcc, 0x77, 0x03, 0xea,
	0x35, 0x77, 0x6d, 0x89, 0xd5, 0x31, 0x90, 0x5f, 0x08, 0x16, 0xb3, 0x68, 0x52, 0x5b, 0x5f, 0x70,
	0xaa, 0x47, 0xa3, 0x7a, 0x8f, 0xc6, 0xb2, 0x1e, 0xe1, 0x7b, 0x30, 0x45, 0x25, 0xbf, 0x31, 0x5e,
	0x1e, 0xad, 0x4c, 0x6f, 0xad, 0x6e, 0x74, 0x8f, 0xb9, 0x94, 0x69, 0xa5, 0xfb, 0xc9, 0x55, 0x98,
	0x94, 0xc6, 0x16, 0x79, 0xf2, 0x29, 0x35, 0xb7, 0x97, 0xe4, 0x03, 0xac, 0xa9, 0x4e, 0x3e, 0xa4,
	0x11, 0xb7, 0x9f, 0x7b, 0x7b, 0xa1, 0x7f, 0xe2, 0xd8, 0xdc, 0x7e, 0xd1, 0x0c, 0xf8, 0x40, 0x51,
	0xc4, 0xab, 0x00, 0x2d, 0xaa, 0x18, 0x2a, 0xf1, 0xbc, 0x64, 0x29, 0x16, 0xf2, 0x1b, 0xc1, 0xf5,
	0x9e, 0x02, 0x06, 0x0a, 0x7c, 0x0f, 0x05, 0x6a, 0x62, 0xc6, 0xf4, 0x89, 0x19, 0xcf, 0x25, 0x86,
	0xc0, 0xcc, 0x9b, 0xc8, 0xf7, 0xda, 0xda, 0x8c, 0x89, 0xe4, 0x7f, 0xc6, 0x46, 0xea, 0x30, 0x5f,
	0xb5, 0xed, 0x76, 0x62, 0x06, 0x0a, 0x63, 0x19, 0xa6, 0x5b, 0xd0, 0x09, 0x88, 0xf4, 0x42, 0x35,
	0x91, 0x4f, 0x08, 0xb0, 0xca, 0x76, 0xf6, 0x97, 0x95, 0x1c, 0xc1, 0x62, 0x8d, 0x1f, 0x73, 0xc1,
	0xff, 0x8b, 0xcb, 0xca, 0x9d, 0x1d, 0xcd, 0xde, 0xd9, 0x2f, 0x08, 0x96, 0x72, 0x44, 0x43, 0xf0,
	0xf6, 0x23, 0x2c, 0x75, 0xe2, 0x3d, 0x78, 0xa1, 0x6c, 0xc2, 0x42, 0x9c, 0x4e, 0x05, 0xaf, 0x46,
	0x05, 0x95, 0xae, 0x77, 0xfb, 0x45, 0xbe, 0x22, 0x58, 0xce, 0x2b, 0x18, 0x42, 0x1c, 0x3c, 0x58,
	0xc9, 0x24, 0x23, 0x16, 0x32, 0x78, 0x38, 0xf4, 0xd9, 0xff, 0x86, 0xe0, 0xd2, 0x29, 0xc2, 0xa1,
	0x78, 0xfe, 0x19, 0xc1, 0x95, 0x83, 0xc0, 0xa6, 0x82, 0x3f, 0x92, 0x48, 0xde, 0x91, 0x1f, 0xba,
	0x54, 0x38, 0x69, 0x59, 0xf6, 0xa9, 0xa7, 0x02, 0x73, 0x71, 0xc6, 0x25, 0xac, 0x72, 0x11, 0xf2,
	0x66, 0xf2, 0x03, 0x41, 0x59, 0xaf, 0xe1, 0xec, 0x83, 0xb2, 0xf5, 0x67, 0x12, 0x2e, 0xaa, 0x13,
	0x6a, 0x27, 0x0c, 0xd8, 0x3e, 0x0f, 0x4f, 0x1c, 0xc6, 0xb1, 0x03, 0x33, 0x6a, 0xaf, 0xc7, 0x37,
	0x35, 0xb3, 0xac, 0xcb, 0x10, 0x37, 0x6f, 0x15, 0xda, 0x2b, 0x3b, 0xef, 0x08, 0xfe, 0x89, 0x60,
	0x35, 0x3f, 0x57, 0xb2, 0x63, 0x05, 0xdf, 0x2f, 0x80, 0xa8, 0x9f, 0x87, 0xe6, 0x83, 0x7e, 0x8f,
	0xa7, 0x1a, 0x19, 0x40, 0xa7, 0x7e, 0x71, 0x45, 0x37, 0xd8, 0xf3, 0x23, 0xc4, 0xbc, 0x51, 0x60,
	0x67, 0x4a, 0x72, 0x0c, 0xe7, 0x33, 0xd5, 0x82, 0x75, 0x81, 0xec, 0xd6, 0xba, 0xcd, 0xf5, 0x62,
	0x9b, 0x53, 0x36, 0x1f, 0x66, 0xb3, 0x2d, 0x09, 0xaf, 0xf7, 0x14, 0xab, 0x06, 0xf5, 0x76, 0xc1,
	0xdd, 0x29, 0xe1, 0x7b, 0x98, 0x3f, 0xd5, 0x0c, 0xf0, 0x76, 0x11, 0xd5, 0xb9, 0x3e, 0x65, 0x6e,
	0x16, 0x3d, 0xa4, 0xb0, 0x7f, 0x47, 0x60, 0xe8, 0xaa, 0x0f, 0xdf, 0xd1, 0x00, 0xf6, 0x68, 0x19,
	0xe6, 0xdd, 0x7f, 0x3e, 0x97, 0xea, 0x71, 0xc1, 0xdc, 0x7f, 0xdd, 0x10, 0x35, 0xff, 0x9d, 0x77,
	0xa0, 0x60, 0xc4, 0xf5, 0xc7, 0x43, 0x7c, 0x4d, 0x03, 0x9c, 0x7d, 0x8e, 0x9b, 0x6b, 0xda, 0x17,
	0x66, 0xe6, 0x8d, 0x4e, 0x46, 0x5e, 0x4e, 0x24, 0x0f, 0xfd, 0xed, 0xbf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x98, 0x87, 0x55, 0xb1, 0x07, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserRequestsGrpcServiceClient is the client API for UserRequestsGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserRequestsGrpcServiceClient interface {
	// List accounts that belongs to Company and that the user is authorized to see
	ListAccounts(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error)
	// List accounts that is of the type the user provided
	ListAccountsBaseOnProvidedType(ctx context.Context, in *ListAccountsBasedOnProvidedTypeRequest, opts ...grpc.CallOption) (*ListAccountsBasedOnProvidedTypeResponse, error)
	// Add an account of a certain type
	AddAccount(ctx context.Context, in *AddAccountRequest, opts ...grpc.CallOption) (*AddAccountResponse, error)
	// Delete an account
	DeleteAccount(ctx context.Context, in *DeleteAccountRequest, opts ...grpc.CallOption) (*DeleteAccountResponse, error)
	// Add an account type
	AddAccountType(ctx context.Context, in *AddAccountTypeRequest, opts ...grpc.CallOption) (*AddAccountTypeResponse, error)
	// Delete an account type
	DeleteAccountType(ctx context.Context, in *DeleteAccountTypeTypeRequest, opts ...grpc.CallOption) (*DeleteAccountTypeResponse, error)
	// Update company information
	UpdateCompanyInformation(ctx context.Context, in *UpdateCompanyInformationRequest, opts ...grpc.CallOption) (*UpdateCompanyInformationResponse, error)
	// Shutdown server in a controlled way
	ShutDownUserRequestsServer(ctx context.Context, in *EmptyParameter, opts ...grpc.CallOption) (*AckNackResponse, error)
}

type userRequestsGrpcServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserRequestsGrpcServiceClient(cc *grpc.ClientConn) UserRequestsGrpcServiceClient {
	return &userRequestsGrpcServiceClient{cc}
}

func (c *userRequestsGrpcServiceClient) ListAccounts(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error) {
	out := new(ListAccountsResponse)
	err := c.cc.Invoke(ctx, "/userRequests_grpc_api.userRequestsGrpcService/ListAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRequestsGrpcServiceClient) ListAccountsBaseOnProvidedType(ctx context.Context, in *ListAccountsBasedOnProvidedTypeRequest, opts ...grpc.CallOption) (*ListAccountsBasedOnProvidedTypeResponse, error) {
	out := new(ListAccountsBasedOnProvidedTypeResponse)
	err := c.cc.Invoke(ctx, "/userRequests_grpc_api.userRequestsGrpcService/ListAccountsBaseOnProvidedType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRequestsGrpcServiceClient) AddAccount(ctx context.Context, in *AddAccountRequest, opts ...grpc.CallOption) (*AddAccountResponse, error) {
	out := new(AddAccountResponse)
	err := c.cc.Invoke(ctx, "/userRequests_grpc_api.userRequestsGrpcService/AddAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRequestsGrpcServiceClient) DeleteAccount(ctx context.Context, in *DeleteAccountRequest, opts ...grpc.CallOption) (*DeleteAccountResponse, error) {
	out := new(DeleteAccountResponse)
	err := c.cc.Invoke(ctx, "/userRequests_grpc_api.userRequestsGrpcService/DeleteAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRequestsGrpcServiceClient) AddAccountType(ctx context.Context, in *AddAccountTypeRequest, opts ...grpc.CallOption) (*AddAccountTypeResponse, error) {
	out := new(AddAccountTypeResponse)
	err := c.cc.Invoke(ctx, "/userRequests_grpc_api.userRequestsGrpcService/AddAccountType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRequestsGrpcServiceClient) DeleteAccountType(ctx context.Context, in *DeleteAccountTypeTypeRequest, opts ...grpc.CallOption) (*DeleteAccountTypeResponse, error) {
	out := new(DeleteAccountTypeResponse)
	err := c.cc.Invoke(ctx, "/userRequests_grpc_api.userRequestsGrpcService/DeleteAccountType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRequestsGrpcServiceClient) UpdateCompanyInformation(ctx context.Context, in *UpdateCompanyInformationRequest, opts ...grpc.CallOption) (*UpdateCompanyInformationResponse, error) {
	out := new(UpdateCompanyInformationResponse)
	err := c.cc.Invoke(ctx, "/userRequests_grpc_api.userRequestsGrpcService/UpdateCompanyInformation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRequestsGrpcServiceClient) ShutDownUserRequestsServer(ctx context.Context, in *EmptyParameter, opts ...grpc.CallOption) (*AckNackResponse, error) {
	out := new(AckNackResponse)
	err := c.cc.Invoke(ctx, "/userRequests_grpc_api.userRequestsGrpcService/ShutDownUserRequestsServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserRequestsGrpcServiceServer is the server API for UserRequestsGrpcService service.
type UserRequestsGrpcServiceServer interface {
	// List accounts that belongs to Company and that the user is authorized to see
	ListAccounts(context.Context, *ListAccountsRequest) (*ListAccountsResponse, error)
	// List accounts that is of the type the user provided
	ListAccountsBaseOnProvidedType(context.Context, *ListAccountsBasedOnProvidedTypeRequest) (*ListAccountsBasedOnProvidedTypeResponse, error)
	// Add an account of a certain type
	AddAccount(context.Context, *AddAccountRequest) (*AddAccountResponse, error)
	// Delete an account
	DeleteAccount(context.Context, *DeleteAccountRequest) (*DeleteAccountResponse, error)
	// Add an account type
	AddAccountType(context.Context, *AddAccountTypeRequest) (*AddAccountTypeResponse, error)
	// Delete an account type
	DeleteAccountType(context.Context, *DeleteAccountTypeTypeRequest) (*DeleteAccountTypeResponse, error)
	// Update company information
	UpdateCompanyInformation(context.Context, *UpdateCompanyInformationRequest) (*UpdateCompanyInformationResponse, error)
	// Shutdown server in a controlled way
	ShutDownUserRequestsServer(context.Context, *EmptyParameter) (*AckNackResponse, error)
}

// UnimplementedUserRequestsGrpcServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserRequestsGrpcServiceServer struct {
}

func (*UnimplementedUserRequestsGrpcServiceServer) ListAccounts(ctx context.Context, req *ListAccountsRequest) (*ListAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAccounts not implemented")
}
func (*UnimplementedUserRequestsGrpcServiceServer) ListAccountsBaseOnProvidedType(ctx context.Context, req *ListAccountsBasedOnProvidedTypeRequest) (*ListAccountsBasedOnProvidedTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAccountsBaseOnProvidedType not implemented")
}
func (*UnimplementedUserRequestsGrpcServiceServer) AddAccount(ctx context.Context, req *AddAccountRequest) (*AddAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAccount not implemented")
}
func (*UnimplementedUserRequestsGrpcServiceServer) DeleteAccount(ctx context.Context, req *DeleteAccountRequest) (*DeleteAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAccount not implemented")
}
func (*UnimplementedUserRequestsGrpcServiceServer) AddAccountType(ctx context.Context, req *AddAccountTypeRequest) (*AddAccountTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAccountType not implemented")
}
func (*UnimplementedUserRequestsGrpcServiceServer) DeleteAccountType(ctx context.Context, req *DeleteAccountTypeTypeRequest) (*DeleteAccountTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAccountType not implemented")
}
func (*UnimplementedUserRequestsGrpcServiceServer) UpdateCompanyInformation(ctx context.Context, req *UpdateCompanyInformationRequest) (*UpdateCompanyInformationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCompanyInformation not implemented")
}
func (*UnimplementedUserRequestsGrpcServiceServer) ShutDownUserRequestsServer(ctx context.Context, req *EmptyParameter) (*AckNackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShutDownUserRequestsServer not implemented")
}

func RegisterUserRequestsGrpcServiceServer(s *grpc.Server, srv UserRequestsGrpcServiceServer) {
	s.RegisterService(&_UserRequestsGrpcService_serviceDesc, srv)
}

func _UserRequestsGrpcService_ListAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRequestsGrpcServiceServer).ListAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userRequests_grpc_api.userRequestsGrpcService/ListAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRequestsGrpcServiceServer).ListAccounts(ctx, req.(*ListAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRequestsGrpcService_ListAccountsBaseOnProvidedType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAccountsBasedOnProvidedTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRequestsGrpcServiceServer).ListAccountsBaseOnProvidedType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userRequests_grpc_api.userRequestsGrpcService/ListAccountsBaseOnProvidedType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRequestsGrpcServiceServer).ListAccountsBaseOnProvidedType(ctx, req.(*ListAccountsBasedOnProvidedTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRequestsGrpcService_AddAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRequestsGrpcServiceServer).AddAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userRequests_grpc_api.userRequestsGrpcService/AddAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRequestsGrpcServiceServer).AddAccount(ctx, req.(*AddAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRequestsGrpcService_DeleteAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRequestsGrpcServiceServer).DeleteAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userRequests_grpc_api.userRequestsGrpcService/DeleteAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRequestsGrpcServiceServer).DeleteAccount(ctx, req.(*DeleteAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRequestsGrpcService_AddAccountType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAccountTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRequestsGrpcServiceServer).AddAccountType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userRequests_grpc_api.userRequestsGrpcService/AddAccountType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRequestsGrpcServiceServer).AddAccountType(ctx, req.(*AddAccountTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRequestsGrpcService_DeleteAccountType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAccountTypeTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRequestsGrpcServiceServer).DeleteAccountType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userRequests_grpc_api.userRequestsGrpcService/DeleteAccountType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRequestsGrpcServiceServer).DeleteAccountType(ctx, req.(*DeleteAccountTypeTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRequestsGrpcService_UpdateCompanyInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCompanyInformationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRequestsGrpcServiceServer).UpdateCompanyInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userRequests_grpc_api.userRequestsGrpcService/UpdateCompanyInformation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRequestsGrpcServiceServer).UpdateCompanyInformation(ctx, req.(*UpdateCompanyInformationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRequestsGrpcService_ShutDownUserRequestsServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyParameter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRequestsGrpcServiceServer).ShutDownUserRequestsServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userRequests_grpc_api.userRequestsGrpcService/ShutDownUserRequestsServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRequestsGrpcServiceServer).ShutDownUserRequestsServer(ctx, req.(*EmptyParameter))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserRequestsGrpcService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "userRequests_grpc_api.userRequestsGrpcService",
	HandlerType: (*UserRequestsGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAccounts",
			Handler:    _UserRequestsGrpcService_ListAccounts_Handler,
		},
		{
			MethodName: "ListAccountsBaseOnProvidedType",
			Handler:    _UserRequestsGrpcService_ListAccountsBaseOnProvidedType_Handler,
		},
		{
			MethodName: "AddAccount",
			Handler:    _UserRequestsGrpcService_AddAccount_Handler,
		},
		{
			MethodName: "DeleteAccount",
			Handler:    _UserRequestsGrpcService_DeleteAccount_Handler,
		},
		{
			MethodName: "AddAccountType",
			Handler:    _UserRequestsGrpcService_AddAccountType_Handler,
		},
		{
			MethodName: "DeleteAccountType",
			Handler:    _UserRequestsGrpcService_DeleteAccountType_Handler,
		},
		{
			MethodName: "UpdateCompanyInformation",
			Handler:    _UserRequestsGrpcService_UpdateCompanyInformation_Handler,
		},
		{
			MethodName: "ShutDownUserRequestsServer",
			Handler:    _UserRequestsGrpcService_ShutDownUserRequestsServer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "userRequests_grpc_api.proto",
}
